---
name: thoughtnav
description: The Mobile Optimized Participant Experience
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.0
  percent_indicator: ^2.1.7+4
  flutter_switch: ^0.1.3
  intl: ^0.16.1
  get_storage: ^1.3.2
  file_picker: ^2.0.11
  csv: ^4.1.0
  cached_network_image: ^2.3.3

  http: ^0.12.2

  firebase: ^8.0.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0

  easy_web_view: ^1.3.1

  reorderables: ^0.3.2

  mask_text_input_formatter: ^1.1.0

  image_picker_web_redux: ^1.1.3

  video_player: ^1.0.1

  flutter_widget_from_html_core: ^0.5.1+4

  chewie: ^0.12.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:

  - images/
  - images/svg_icons/
  - images/dashboard_icons/
  - images/set_account_icons/
  - images/questions_icons/
  - images/homescreen_images/
  - images/login_section_images/
  - images/researcher_images/researcher_dashboard/


  fonts:
    - family: Sofia
      fonts:
        - asset: assets/fonts/sofia_pro_regular.otf

# ThoughtNav. Focus Groups. Made Easy.
# © Aperio Insights 30th April 2021. Version 1.0.0
# All Rights Reserved