name: thoughtnav
description: The Mobile Optimized Participant Experience

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  flutter_svg: ^0.18.0

  websafe_svg: ^1.1.4

  carousel_slider: ^2.2.1

  dotted_border: ^1.0.6

  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/svg_icons/
    - images/avatars/
    - images/dashboard_icons/
    - images/set_account_icons/