---
name: thoughtnav
description: The Mobile Optimized Participant Experience
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  percent_indicator: ^4.0.0
  flutter_switch: ^0.3.2
  intl: ^0.17.0
  get_storage: ^2.0.3
  file_picker: ^4.5.0
  csv: ^5.0.1
  cached_network_image: ^3.2.0

  http: ^0.13.4

  firebase: ^9.0.2
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  firebase_storage: ^8.0.0-1.0.nullsafety.1

#  easy_web_view2: ^0.0.3

  reorderables: ^0.4.3

  mask_text_input_formatter: ^2.1.0

  image_picker_web_redux: ^2.0.1

  video_player: ^2.2.19

  flutter_widget_from_html_core: ^0.8.5+1

  chewie: ^1.3.0

  get: ^4.2.4

  webview_flutter_web: ^0.1.0+1
  webview_flutter: ^3.0.1

dependency_overrides:
  firebase_storage: ^10.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:

  - images/
  - images/svg_icons/
  - images/dashboard_icons/
  - images/set_account_icons/
  - images/questions_icons/
  - images/homescreen_images/
  - images/login_section_images/
  - images/researcher_images/researcher_dashboard/


  fonts:
    - family: Sofia
      fonts:
        - asset: assets/fonts/sofia_pro_regular.otf

# ThoughtNav. Focus Groups. Made Easy.
# © Aperio Insights 30th April 2021. Version 1.0.0
# All Rights Reserved