---
name: thoughtnav
description: The Mobile Optimized Participant Experience
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0
  websafe_svg: ^1.1.4
  carousel_slider: ^2.2.1
  dotted_border: ^1.0.6
  auto_size_text: ^2.1.0
  google_fonts: ^1.1.0
  percent_indicator: ^2.1.7+4
  flutter_switch: ^0.1.3

  firebase: ^7.3.0
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - images/
  - images/svg_icons/
  - images/avatars/
  - images/dashboard_icons/
  - images/set_account_icons/
  - images/questions_icons/
  - images/reward_icons/
  - images/homescreen_images/
  - images/login_section_images/
  - images/researcher_images/researcher_dashboard/
  - images/study_categories/
